name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'bind9/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        PROJECT: 'geyserconnect'

    steps:
      - name: Get Release Info
        id: release-info
        uses: GeyserMC/actions/previous-release@master
        with:
          data: ${{ vars.RELEASEACTION_PREVRELEASE }}
          
      - run: | 
          echo "Previous release: ${{ steps.release-info.outputs.previousRelease }}"
          echo "Current release: ${{ steps.release-info.outputs.curentRelease }}"

      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 17

      - name: Build GeyserConnect
        run: ./gradlew build

      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: build/libs/GeyserConnect.jar

      - name: Get Version
        if: ${{ success() && github.repository == 'GeyserMC/actions-testing' && github.ref_name == 'master' }}
        id: get-version
        run: | 
          version=$(cat build.gradle | grep -o "version '[0-9\\.]*'" | cut -d" " -f2 | sed "s/'//g")
          echo "VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Get Release Metadata
        if: ${{ success() && github.repository == 'GeyserMC/actions-testing' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/release@master
        id: metadata
        with:
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          files: |
            geyserconnect:build/libs/GeyserConnect.jar
          releaseEnabled: false
          saveMetadata: true
          releaseProject: 'geyserconnect'
          releaseVersion: ${{ steps.get-version.outputs.VERSION }}

      - name: Publish to Downloads API
        if: ${{ success() && github.repository == 'GeyserMC/actions-testing' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/upload-release@master
        with:
          username: ${{ secrets.TEST_DOWNLOADS_USERNAME }}
          privateKey: ${{ secrets.TEST_DOWNLOADS_PRIVATE_KEY }}
          host: ${{ secrets.TEST_DOWNLOADS_SERVER_IP }}
          port: '2133'
          files: |
            build/libs/GeyserConnect.jar
          changelog: ${{ steps.metadata.outputs.body }}

      - name: Notify Discord
        if: ${{ github.repository == 'GeyserMC/actions-testing' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/notify-discord@master
        with:
          discordWebhook: ${{ secrets.TEST_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          body: ${{ steps.metadata.outputs.body }}
