name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'bind9/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        PROJECT: 'geyserconnect'

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build GeyserConnect
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: GeyserConnect
          path: build/libs/GeyserConnect.jar
          
      - name: Get Release Metadata
        if: ${{ success() && github.repository == 'GeyserMC/GeyserConnect' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/release@master
        with:
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          files: |
            geyserconnect:build/libs/GeyserConnect.jar
          releaseEnabled: false
          saveMetadata: true

      - name: Publish to Downloads API
        if: ${{ success() && github.repository == 'GeyserMC/GeyserConnect' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/upload-release@master
        with:
          username: ${{ secrets.DOWNLOADS_USERNAME }}
          privateKey: ${{ secrets.DOWNLOADS_PRIVATE_KEY }}
          host: ${{ secrets.DOWNLOADS_SERVER_IP }}
          files: |
            build/libs/GeyserConnect.jar
